"""Shared helper functions for the selection module"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/helpers.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/components/helpers.ipynb #66f38929
from typing import List

from cjm_fasthtml_interactions.core.context import InteractionContext
from cjm_source_provider.models import SelectedSource
from ..models import SelectionStepState

# %% ../../nbs/components/helpers.ipynb #d2384ace
def _get_selection_state(
    ctx: InteractionContext  # Interaction context with state
) -> SelectionStepState:  # Typed selection step state
    """Get the full selection step state from context."""
    step_states = ctx.state.get("step_states", {})
    return step_states.get("selection", {})

# %% ../../nbs/components/helpers.ipynb #93redrqtcwo
def _get_selected_sources(
    ctx: InteractionContext  # Interaction context with state
) -> List[SelectedSource]:  # List of selected source dicts
    """Get the list of selected sources from step state."""
    state = _get_selection_state(ctx)
    return state.get("selected_sources", [])

# %% ../../nbs/components/helpers.ipynb #8mza4710z6
def _get_grouping_mode(
    ctx: InteractionContext  # Interaction context with state
) -> str:  # Grouping mode: "media_path" or "batch_id"
    """Get the current grouping mode from step state."""
    state = _get_selection_state(ctx)
    return state.get("grouping_mode", "media_path")

# %% ../../nbs/components/helpers.ipynb #264e90b1
def _generate_sortable_init_script(
    container_selector: str = ".sortable",  # CSS selector for sortable containers
    handle_selector: str = ".drag-handle",  # CSS selector for drag handles
    animation_ms: int = 150,  # Animation duration in milliseconds
) -> str:  # JavaScript initialization script
    """Generate Sortable.js initialization script for htmx integration."""
    return f"""
htmx.onLoad(function(content) {{
    var sortables = content.querySelectorAll("{container_selector}");
    for (var i = 0; i < sortables.length; i++) {{
        var sortable = sortables[i];
        var sortableInstance = new Sortable(sortable, {{
            animation: {animation_ms},
            handle: "{handle_selector}",
            
            // Disable sorting on the 'end' event (prevents double-firing)
            onEnd: function (evt) {{
                this.option("disabled", true);
            }}
        }});
        
        // Re-enable sorting after htmx swap completes
        sortable.addEventListener("htmx:afterSwap", function() {{
            sortableInstance.option("disabled", false);
        }});
    }}
}});
"""
