"""Collapsible preview panel for displaying selected content"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/preview_panel.ipynb.

# %% auto #0
__all__ = []

# %% ../../nbs/components/preview_panel.ipynb #72dd90f9
from typing import Any, Optional

from fasthtml.common import Div, H3, P, Span, Input

# DaisyUI components
from cjm_fasthtml_daisyui.components.data_display.collapse import (
    collapse, collapse_title, collapse_content, collapse_modifiers
)
from cjm_fasthtml_daisyui.utilities.semantic_colors import bg_dui, text_dui, border_dui
from cjm_fasthtml_daisyui.utilities.border_radius import border_radius

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, max_h
from cjm_fasthtml_tailwind.utilities.typography import (
    font_size, font_weight, font_family, text_align, whitespace, italic
)
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.borders import border
from cjm_fasthtml_tailwind.utilities.effects import shadow
from cjm_fasthtml_tailwind.core.base import combine_classes

# Local imports
from ..html_ids import SelectionHtmlIds

# %% ../../nbs/components/preview_panel.ipynb #adf55484
def _render_preview_panel(
    preview_record_id: Optional[str] = None,  # Job ID being previewed
    preview_text: Optional[str] = None,  # Text content to preview
    is_open: bool = False,  # Whether the collapse should be open
) -> Any:  # Preview panel component (collapsible, full-width)
    """Render the collapsible preview panel for displaying selected content."""
    has_preview = preview_record_id and preview_text
    
    # Determine collapse state - open if content and is_open flag is True
    should_be_open = has_preview and is_open
    
    # Empty state content
    empty_content = Div(
        "Select a row to preview content",
        cls=combine_classes(
            text_dui.base_content.opacity(30),
            italic,
            p.y(8),
            text_align.center
        )
    )
    
    # Preview content
    preview_content = Div(
        # Job ID header
        H3(
            preview_record_id,
            cls=combine_classes(font_size.xs, font_family.mono, text_dui.base_content.opacity(50), m.b(2))
        ),
        # Text content with scroll
        Div(
            P(preview_text, cls=combine_classes(whitespace.pre_wrap, font_size.sm)),
            cls=combine_classes(max_h(48), overflow.y.auto)
        )
    ) if has_preview else empty_content
    
    return Div(
        # Checkbox for collapse control
        Input(
            type="checkbox",
            checked="checked" if should_be_open else None,
            id=SelectionHtmlIds.PREVIEW_COLLAPSE_TOGGLE
        ),
        # Collapse title (clickable header)
        Div(
            Span("Content Preview", cls=str(font_weight.semibold)),
            Span(
                f"({preview_record_id[:12]}...)" if preview_record_id and len(preview_record_id) > 12 else f"({preview_record_id})" if preview_record_id else "",
                cls=combine_classes(font_size.xs, font_family.mono, text_dui.base_content.opacity(50), m.l(2))
            ) if preview_record_id else None,
            cls=combine_classes(collapse_title, font_size.sm)
        ),
        # Collapse content
        Div(
            preview_content,
            id=SelectionHtmlIds.PREVIEW_CONTENT,
            cls=combine_classes(collapse_content, p(4), bg_dui.base_200.opacity(30))
        ),
        id=SelectionHtmlIds.PREVIEW_PANEL,
        cls=combine_classes(
            collapse,
            collapse_modifiers.arrow,
            w.full,
            bg_dui.base_100,
            border_radius.box,
            shadow.lg,
            border_dui.base_300,
            border(),
            m.t(4)
        )
    )
