"""HTML ID constants for Phase 1: Source Selection & Ordering"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['SelectionHtmlIds']

# %% ../nbs/html_ids.ipynb #c3d4e5f6
# Framework-agnostic — no external imports needed

class SelectionHtmlIds:
    """HTML ID constants for Phase 1: Source Selection & Ordering."""

    @staticmethod
    def as_selector(
        id_str:str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Main container
    SOURCE_SELECTOR = "sd-source-selector"

    # Tabs
    SOURCE_TABS = "sd-source-tabs"
    SOURCE_TAB_DB = "sd-source-tab-db"
    SOURCE_TAB_FILES = "sd-source-tab-files"
    SOURCE_TAB_CONTENT = "sd-source-tab-content"

    # Browser Panel
    SOURCE_BROWSER = "sd-source-browser"
    SOURCE_LIST = "sd-source-list"
    SOURCE_FILTER_PLUGIN = "sd-source-filter-plugin"
    SOURCE_FILTER_SEARCH = "sd-source-filter-search"
    GROUPING_SELECTOR = "sd-grouping-selector"

    # Queue Panel
    QUEUE_PANEL = "sd-queue-panel"
    QUEUE_CONTAINER = "sd-queue-container"
    QUEUE_LIST = "sd-queue-list"
    QUEUE_EMPTY = "sd-queue-empty"
    SOURCE_ORDER_LIST = "sd-source-order-list"
    SELECTED_SOURCES = "sd-selected-sources"

    # Preview Panel
    PREVIEW_PANEL = "sd-preview-panel"
    PREVIEW_COLLAPSE = "sd-preview-collapse"
    PREVIEW_COLLAPSE_TOGGLE = "sd-preview-collapse-toggle"
    PREVIEW_CONTENT = "sd-preview-content"
    PREVIEW_HEADER = "sd-preview-header"
    PREVIEW_EMPTY = "sd-preview-empty"

    # Keyboard Actions
    KB_ACTION_BUTTONS = "sd-kb-action-buttons"

    # Local Files Browser
    LOCAL_FILES_BROWSER = "sd-local-files-browser"
    LOCAL_FILES_LIST = "sd-local-files-list"
    EXTERNAL_SOURCES_LIST = "sd-external-sources-list"

    # Footer
    SELECTION_FOOTER = "sd-selection-footer"
    SELECTION_STATS = "sd-selection-stats"

    # Script runner (OOB container for flash feedback scripts)
    SCRIPT_RUNNER = "sd-selection-script-runner"

    @staticmethod
    def _safe_id(
        value:str  # Raw value to sanitize for HTML ID use
    ) -> str:  # Sanitized string safe for HTML IDs
        """Sanitize a string for use in HTML IDs."""
        return value.replace(":", "-").replace("_", "-")

    @staticmethod
    def source_checkbox(
        record_id:str,  # Record identifier
        provider_id:str  # Provider identifier
    ) -> str:  # HTML ID for the source checkbox
        """Generate HTML ID for a source selection checkbox."""
        safe_rec = SelectionHtmlIds._safe_id(record_id)
        safe_prov = SelectionHtmlIds._safe_id(provider_id)
        return f"sd-source-cb-{safe_prov}-{safe_rec}"

    @staticmethod
    def source_row(
        record_id:str,  # Record identifier
        provider_id:str  # Provider identifier
    ) -> str:  # HTML ID for the source row
        """Generate HTML ID for a source browser row."""
        safe_rec = SelectionHtmlIds._safe_id(record_id)
        safe_prov = SelectionHtmlIds._safe_id(provider_id)
        return f"sd-source-row-{safe_prov}-{safe_rec}"

    @staticmethod
    def queue_item(
        record_id:str,  # Record identifier
        provider_id:str  # Provider identifier
    ) -> str:  # HTML ID for the queue item
        """Generate HTML ID for a queue item."""
        safe_rec = SelectionHtmlIds._safe_id(record_id)
        safe_prov = SelectionHtmlIds._safe_id(provider_id)
        return f"sd-queue-item-{safe_prov}-{safe_rec}"
