"""Data models and URL bundles for Phase 1: Source Selection & Ordering"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/models.ipynb.

# %% auto #0
__all__ = ['SelectionStepState', 'SelectionUrls']

# %% ../nbs/models.ipynb #selection-models-imports
from typing import List, Dict, Any
from typing_extensions import TypedDict
from dataclasses import dataclass

from cjm_source_provider.models import SelectedSource

# %% ../nbs/models.ipynb #selection-step-state
class SelectionStepState(TypedDict, total=False):
    """State for Phase 1: Source Selection & Ordering."""

    selected_sources: List[SelectedSource]  # Ordered list of selected sources
    grouping_mode: str  # Grouping mode: "media_path" or "batch_id"
    external_db_paths: List[str]  # List of external database paths
    current_browse_path: str  # Current directory in local files browser
    file_browser_state: Dict[str, Any]  # Serialized BrowserState from file-browser library

# %% ../nbs/models.ipynb #selection-urls
@dataclass
class SelectionUrls:
    """URL bundle for Phase 1 selection route handlers and renderers."""

    # Queue operations
    add: str = ""  # Add source to queue
    remove: str = ""  # Remove source from queue
    reorder: str = ""  # Reorder queue items
    clear: str = ""  # Clear all from queue
    select_all: str = ""  # Select all in a group
    preview: str = ""  # Preview source content

    # Keyboard actions
    toggle_focused: str = ""  # Toggle focused row selection
    keyboard_reorder: str = ""  # Keyboard reorder (Shift+Up/Down)

    # Filtering and grouping
    filter: str = ""  # Filter source list
    grouping_change: str = ""  # Change grouping mode

    # Local files browser
    browse_directory: str = ""  # Browse directory
    add_external: str = ""  # Add external .db source
    remove_external: str = ""  # Remove external .db source

    # Tab switching
    tab_switch: str = ""  # Switch source tabs
